### ISSUE TITLE
send and receiving a video?

### ISSUE THREAD

**Issue by Thanh-Binh** [ultravideo/uvgRTP#11]
I am trying to use examples in the document for sending and receiving (pooling).
when I set
#define PAYLOAD_MAXLEN 1000
and got a correct receiving
```
value: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 
value: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 
value: 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 
value: 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 
value: 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 
value: 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 
value: 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 
value: 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 
value: 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 
value: 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 
```
For data length bigger than 10000, by setting
#define PAYLOAD_MAXLEN 10000
 I do not receive data correctly.
```
value: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 
value: 0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 
value: 2, 1, 4, 5, 6, 7, 8, 9, 10, 11, 
value: 2, 1, 5, 6, 7, 8, 9, 10, 11, 12, 
value: 4, 1, 6, 7, 8, 9, 10, 11, 12, 13, 
value: 4, 1, 7, 8, 9, 10, 11, 12, 13, 14, 
value: 6, 1, 8, 9, 10, 11, 12, 13, 14, 15, 
value: 6, 1, 9, 10, 11, 12, 13, 14, 15, 16, 
value: 8, 1, 10, 11, 12, 13, 14, 15, 16, 17, 
value: 8, 1, 11, 12, 13, 14, 15, 16, 17, 18,
```

here is my code for sending:
```
for (int i = 0; i < 10; ++i) {
      for (auto j=0; j < 10; ++j) buffer[j] = (uint8_t)i+j;
      if (hevc->push_frame(buffer, PAYLOAD_MAXLEN, RTP_NO_FLAGS) != RTP_OK)
        fprintf(stderr, "Failed to send RTP frame!");
      std::this_thread::sleep_for(std::chrono::milliseconds(50));
    }
```
and receiving:
```
while ((frame = hevc->pull_frame()) != nullptr) 
    {
        if (frame->payload_len)
        {
            printf("value: ");
            for (auto i=0; i < 10; ++i) printf("%d, ", frame->payload[i]);
            printf("\n");
        }
        /* When we receive a frame, the ownership of the frame belongs to us and
         * when we're done with it, we need to deallocate the frame */
        (void)uvg_rtp::frame::dealloc_frame(frame);
    }
```
I really do NOT understand why RTP causes problem by sending big data like video??
Could you please help me?

**Comment by altonen** [comment]
Hello,

uvgRTP uses an 8 KB buffer in the receiving end for datagrams so any packet larger than that is currently incorrectly handled. I'll push a fix later this week that'll increase the size to 65 KB which is the actual maximum size which can be expected so thank you for reporting this bug.

In the mean time, there are two different ways of temporarily fixing this. First is to set the value `recv_buffer_len` in [1] to 10000 and recompile uvgRTP. This should fix the issue but I'm not 100% certain if that is the only place where this 8 KB max size assumption is made so it may not work.

Another way of fixing this is to provide `RCE_FRAGMENT_GENERIC` in the flags parameter when you're creating the media. This will fragment the input frame given to `push_frame` to RTP frames of 1500 bytes and the RTP receiver will reconstruct the full frame from the fragments when `pull_frame` is called, [2] shows you how to do that

[1] https://github.com/ultravideo/uvgRTP/blob/master/src/pkt_dispatch.cc#L216
[2] https://github.com/ultravideo/uvgRTP/blob/master/docs/examples/sending_generic.cc

**Comment by Thanh-Binh** [comment]
Thanks for your response.
Why is the data length limited by 65Kbytes?
It is much lower than VGA gray.scaled images!

**Comment by altonen** [comment]
It's determined by IPv4 packet's max size which is 65 KB. If you want to send larger frames, there are several RFCs which define how a certain media type should be fragmented and transported over the network, e.g., RFC 7798 for HEVC. Because we don't have the manpower to implement all of these payload formats, we've instead implemented a generic interface which can be used to fragment any media. The only problem is that it only works with uvgRTP so you need to use it for both sending and receiving.

**Comment by Thanh-Binh** [comment]
@altonen thanks.
I understood: because the max size is 65KB so that we have to use RCE_FRAGMENT_GENERIC
But do not understand why this mode sends multiple packets of 1.5KB. Why 1.5KB?

**Comment by altonen** [comment]
Maximum transmission unit (MTU) [1] defines the size for an Ethernet frame and 1500 bytes is probably the most commonly used size. Basically uvgRTP just tries to fill each Ethernet frame with as much data as possible. You can change this 1.5 KB limit to some other value you find suitable using `RCC_MTU_SIZE` [2]. For example, if you wanted to fragment the input into frames of 5000 bytes, you would call `hevc->configure_ctx(RCC_MTU_SIZE, 5000);`.

[1] https://en.wikipedia.org/wiki/Maximum_transmission_unit
[2] https://ultravideo.github.io/uvgRTP/html/classuvgrtp_1_1media__stream.html#addf1cde9cb8c4e4af3160ce24c4288a5

**Comment by Thanh-Binh** [comment]
Thanks
I have just tested for sending a big data with fragment generic, it works well! 
but I want to inform the receiver the image information like width, height, depth etc by initialization!
That means I have to send a small data (4 x 32bits data = 16bytes) firstly .
But I can not receive those data!
Are small data discarded before sending?
Thanks

**Comment by Thanh-Binh** [comment]
Clear that is limited by 65KBytes but it is bug that smaller data than defined packet value (here 1.5K) is discarded!

**Comment by altonen** [comment]
Hi and sorry for the long wait.

You're absolutely correct that discarding small packets is not correct. I believe I fixed this and there's even a test case in `docs/examples/sending_generic.cc` which demonstrates that both large and small packets can be sent through the interface. Looking at the implementation I cannot spot where the bug is so I'll have to write more robust test cases to reveal it. Unfortunately I don't have the time to do that right now.

The hackiest hack I can come up with off the top of my head is to pad your control data (width, height, depth etc.) to, for example, 2000 bytes with zeros and then send that data through the interface. uvgRTP will fragment that into smaller packets and you can receive the whole 2 KB block and then just extract your information from that larger block. This solution is ugly beyond words but it should work if you're able to receive large packets but not small ones.

**Comment by Thanh-Binh** [comment]
May be you forgot to update it!
I see the last change 14 days as go

**Comment by Thanh-Binh** [comment]
@altonen Could you please change for supporting 65KBytes?
I really need it for Kvazzup, which does not work correctly with audio. Thanks

**Comment by altonen** [comment]
It's in master now, I did it last week but forgot to push it to Github.

I'll try to investigate what the issue is with small frames when RCE_FRAGMENT_GENERIC is used

**Comment by Thanh-Binh** [comment]
Thanks
I am Investing now on echo problem with audio in Kvazzup, which relates to uvgRTP
