### ISSUE TITLE
Got errors when include lib.hh before QVideoFrame(or other qt files)

### ISSUE THREAD

**Issue by HikariS97** [ultravideo/uvgRTP#2]
`#include <kvzrtp/lib.hh>`
`#include <QVideoFrame>`

![微信截图_20200506083419](https://user-images.githubusercontent.com/48763518/81128703-7cbd9900-8f74-11ea-865a-af37d7812536.png)

once I reverse the including order of two files:
`#include <QVideoFrame>`
`#include <kvzrtp/lib.hh>`

Errors disappear. Seems like something with macros define confliction.

**Comment by altonen** [comment]
hello,
thank you for the bug report! I was unable to reproduce this but according to the image you've attached it's a clear bug. I've pushed a fix to Github and this should no longer be an issue.
Notice that we have renamed the library from kvzRTP to uvgRTP and if you pull the newest changes, you must update your code

**Comment by HikariS97** [comment]
Thanks for your remind. 
I notice this bug may confict against <QDebug>. Even if I set the include files in such a certain order, and then I can build the project successfully, I still can't use qDebug() normally when I need it. The error prompts " Too few arguments provided to function-like macro invocation". 
I hope this can help to fix.
